# Azure Pipelines definition (YAML format)

# YAML schema reference
# https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
