# Azure Pipelines definition (YAML format)

# YAML schema reference
# https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema

trigger:
  - master

pool:
  vmImage: ubuntu-latest

steps:
  - task: AzureWebApp
    inputs:
      azureSubscription: a8060647-8f7f-47ca-bec3-e79e4ab2bcdf
      appType: webAppLinux
      appName: ingress
      package:
