services:
  blob:
    image: mcr.microsoft.com/azure-blob-storage
  meta:
    image: mongo
  ingress:
    build:
      context: .
      dockerfile: ingress/Dockerfile
  egress:
    image: python:slim-bullseye
