# Development environment
# Mock the Azure environment
services:

  # Emulator for Azure Blob Storage
  blob:
    image: mcr.microsoft.com/azure-storage/azurite

  # Emulator for Azure Cosmo DB
  # This is a document-store (NoSQL) database
  meta:
    image: mongo
    volumes:
      # Import scripts
      - ./meta:/meta

  # Web interface to view the MongoDB instance
  meta-admin:
    image: mongo-express
    ports:
      - "81:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=meta

  # Web app for data entry user interface
  app:
    build:
      context: .
      dockerfile: owast/Dockerfile
    volumes:
      # Allow editing of files without rebuilding images
      - ./owast:/owast
    ports:
      - "80:8000"
    environment:
      - FLASK_ENV=development
      - MONGO_URI=mongodb://meta:27017/owast
      - BIND=0.0.0.0:8000
      - WSGI_APP=owast.app_factory:create_app()
      - CHDIR=/
      # Auto-reload upon code change
      - RELOAD=True
    restart: always
