services:
  blob:
    image: mcr.microsoft.com/azure-blob-storage
  meta:
    image: mongo
  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    volumes:
      # Allow editing of files without rebuilding images
      - ./app:/app
    ports:
      - 8000:8000
