# Development environment
services:

  blob:
    image: mcr.microsoft.com/azure-blob-storage

  meta:
    image: mongo
    volumes:
      # Import scripts
      - ./meta:/meta

  app:
    build:
      context: .
      dockerfile: owast/Dockerfile
    volumes:
      # Allow editing of files without rebuilding images
      - ./owast:/owast
    ports:
      - 8000:8000
    environment:
      - FLASK_ENV=development
    restart: always
