# Development environment
services:

  # Emulator for Azure Blob Storage
  blob:
    image: mcr.microsoft.com/azure-storage/azurite

  # Azure Cosmo DB emulator
  meta:
    image: mongo
    volumes:
      # Import scripts
      - ./meta:/meta

  # Web app for data entry
  app:
    build:
      context: .
      dockerfile: owast/Dockerfile
    volumes:
      # Allow editing of files without rebuilding images
      - ./owast:/owast
    ports:
      - 8000:8000
    environment:
      - FLASK_ENV=development
      - MONGO_URI=mongodb://meta:27017/owast
    restart: always
